### ISSUE TITLE
issue #1 :)

### ISSUE THREAD

**Issue by makc** [nicoptere/raymarching-for-THREE#1]
issue #1 :) on my mac the demo looks like this:

![screen shot 2015-11-13 at 19 59 16](https://cloud.githubusercontent.com/assets/242577/11154674/1e8e634c-8a41-11e5-85bf-7a5880140990.png)

it is some shader problem there.

**Comment by makc** [comment]
seems to be fixed in https://twitter.com/nicoptere/status/665638394534502400 did you do anything specific, or was that just lucky coincidence?

**Comment by nicoptere** [comment]
yo hey!
no fucking clue ^^' I'm changing things very often in no specific order ; this will happen again. 
in this case, from the shape of the yellow patch, it looks like the 'squarified pixels' were not square. 
but also depth mayhem... glad it was fixed :p
